### ISSUE TITLE
Game occasionally crashes when using student notebook near corners of realms

### ISSUE THREAD

**Issue by Lowie375** [ubc-minetest-classroom/Minetest_Classroom#202]
**Describe the bug**
When using the student notebook tool near the corner of a realm, attempting to open the "Map" tab sometimes causes the game to crash. I think this is due to a bug in the `mc_mapper` mod (the mod which generates the map)

**To Reproduce**
1. Travel to one of the corners of a realm (with 5 blocks of each realm wall)
2. Left-click with the student notebook tool to open the notebook
3. Click on the "Map" tab of the student notebook
4. Game crashes

**Expected behavior**
The map tab should successfully open and  display a map of the player's current realm

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minetest Version 5.7.0

**Additional context**
This doesn't seem to be tied to a specific realm: it's happen in multiple different ones. It also seems to happen fairly inconsistently, and I've received two different (but similar) debug logs on crash, which I'll attach below

Log 1:
```
AsyncErr: Lua: Runtime error from mod '' in callback on_playerReceiveFields(): ...st\minetest-5.7.0-win64\bin\..\builtin\common\item_s.lua:205: bad argument #1 to '__index' (number expected, got nil)
stack traceback:
 	[C]: in function '__index'
 	...st\minetest-5.7.0-win64\bin\..\builtin\common\item_s.lua:205: in function 'get_name_from_content_id'
 	...\bin\..\games\Minetest_Classroom\mods\mc_mapper\init.lua:149: in function 'map_handler'
 	...\bin\..\games\Minetest_Classroom\mods\mc_student/gui.lua:201: in function <...\bin\..\games\Minetest_Classroom\mods\mc_student/gui.lua:174>
 	...\bin\..\games\Minetest_Classroom\mods\mc_student/gui.lua:521: in function 'show_notebook_fs'
 	....\games\Minetest_Classroom\mods\mc_student/callbacks.lua:118: in function <....\games\Minetest_Classroom\mods\mc_student/callbacks.lua:104>
 	...st\minetest-5.7.0-win64\bin\..\builtin\game\register.lua:446: in function <...st\minetest-5.7.0-win64\bin\..\builtin\game\register.lua:432>
```

Log 2:
```
AsyncErr: Lua: Runtime error from mod '' in callback on_playerReceiveFields(): ...\bin\..\games\Minetest_Classroom\mods\mc_mapper\init.lua:149: attempt to index a nil value
stack traceback:
	...\bin\..\games\Minetest_Classroom\mods\mc_mapper\init.lua:149: in function 'map_handler'
	...\bin\..\games\Minetest_Classroom\mods\mc_student/gui.lua:201: in function <...\bin\..\games\Minetest_Classroom\mods\mc_student/gui.lua:174>
	...\bin\..\games\Minetest_Classroom\mods\mc_student/gui.lua:521: in function 'show_notebook_fs'
	....\games\Minetest_Classroom\mods\mc_student/callbacks.lua:118: in function <....\games\Minetest_Classroom\mods\mc_student/callbacks.lua:104>
	...st\minetest-5.7.0-win64\bin\..\builtin\game\register.lua:446: in function <...st\minetest-5.7.0-win64\bin\..\builtin\game\register.lua:432>
```

**Comment by pauldpickell** [comment]
I was not able to reproduce this error with Windows 10 and MT 5.7.0 in the default spawn realm for MC. However, I have added a check to the offending line 149 in `mc_mapper` for Log 2  ([516b864](https://github.com/ubc-minetest-classroom/minetest_classroom/commit/516b8645f1eaf722f8a3e2967da684309c67ea38)). Log 1 seems to be the same error, it's just caught later in the `builtin` function instead.

Leaving this open as I am unsure if this solves it and there is a related issue: The `realmMapCache` seems to repeat the inside of the realm into the map space outside of the realm specifically at the minimum x-limit side of the realm. The max z-limit side of the realm seems to show unbreakable map barrier outside of the realm. The maximum x-limit side of the realm also shows unbreakable map barrier outside of the realm. Only the minimum z-limit side of the realm seems to correctly display grey outside of the realm boundary.

**Comment by pauldpickell** [comment]
Okay, I have solved the issue above by checking that we are within the realm boundary and also fixing a typo ([eb566cf](https://github.com/ubc-minetest-classroom/minetest_classroom/commit/eb566cfb7ba21bc16d686d7505193a48400590c5)). Closing now as this should solve the earlier issue of pulling a nil content id (presumably outside of the realm near the corners).

**Comment by Lowie375** [comment]
I'm still experiencing crashes (of the log 2 form) when playing with the patched version - will investigate further

**Comment by Lowie375** [comment]
Okay, I think I've got a patch for it - adding some additional checks and moving the `k` and `p2` assignments into the conditional seems to have worked. Will open a PR shortly
